SGD/Models/ErrorViewModel.cs
using System;

namespace SGD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SGD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SGD.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SGD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SGD/Controllers/PaisController.cs
using Microsoft.AspNetCore.Mvc;
using SGD.Data.Interfaces;
using SGD.Data.Model;
using System.Linq;
using System.Threading.Tasks;

namespace SGD.Controllers
{
    public class PaisController : Controller
    {
        private readonly IPaisRepository _paisRepository;

        public PaisController(IPaisRepository paisRepository)
        {
            _paisRepository = paisRepository;
        }

        #region Listar Todos
        public async Task<IActionResult> Index(string sortOrdery)
        {
            ViewBag.sortOrder = sortOrdery;

            var dados = await _paisRepository.ListarTodosAsync();
            var resultDados = dados.OrderBy(p => p.Nome);


            #region Ordenar Por
            if (sortOrdery == "Asc")
            {
                var listarSortOrdery = resultDados.OrderBy(c => c.Nome);
                return View(listarSortOrdery);
            }
            else if (sortOrdery == "Desc")
            {
                var listarSortOrdery = resultDados.OrderByDescending(c => c.Nome);
                return View(listarSortOrdery);
            }
            else
            {
                var listarSortOrdery = resultDados.OrderBy(c => c.Nome);
                return View(listarSortOrdery);
            }
            #endregion
        }
        #endregion


        #region Detalhe 
        //Get: Pais/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var dados = await _paisRepository.PesquisarPorIdAsync(id);
            if (dados == null) return View("NotFound");
            return View(dados);
        }
        #endregion

        #region Actualizar
        //Get: Pais/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var dados = await _paisRepository.PesquisarPorIdAsync(id);
            if (dados == null) return View("NotFound");
            return View(dados);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Nome")] Pais pais)
        {
            if (!ModelState.IsValid)
            {
                return View(pais);
            }
            await _paisRepository.AtualizarAsync(pais);
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Cadastrar
        //Get: Pais/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Nome")] Pais pais)
        {
            if (!ModelState.IsValid)
            {
                return View(pais);
            }
            await _paisRepository.CadastrarAsync(pais);
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region
        /*

        #region Apagar
        //Get: Pais/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var dado = await _pais.PesquisarPorIdAsync(id);
            if (dado == null) return View("NotFound");
            return View(dado);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDelete = await _pais.PesquisarPorIdAsync(id);
            if (actorDelete == null) return View("NotFound");

            //await _pais.ExcluirAsync(id);
            return RedirectToAction(nameof(Index));
        }
        #endregion
         
         */

        #endregion
    }
}

SGD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SGD/Views/Pais/Create.cshtml
@model Pais

@{
    ViewData["Title"] = "Editar País";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    
                    <h1>>> Novo Registro << </h1>
                    <hr />
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control"/>
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <hr />
                    <div class="form-row float-right">
                        <div class="btn-group">
                            <input type="submit" value="Salvar" class="btn btn-outline-success" />
                            <a class="btn btn-outline-secondary" asp-controller="Pais"  asp-action="Index">Voltar</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

SGD/Views/Pais/Details.cshtml
@model Pais

@{
    ViewData["Title"] = "Detalhe País";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <div class="row">
            <div class="col-md-8 offset-2">
            <p>
                <h1>@Model.Nome</h1>
            </p>
                <hr />
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" readonly/>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

                <hr />
                <div class="form-row float-right">
                    <div class="btn-group">
                        <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SGD/Views/Pais/Edit.cshtml
@model Pais

@{
    ViewData["Title"] = "Editar País";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    
                    <h1>>> @Html.DisplayFor(m => Model.Nome) << </h1>
                    <hr />
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control"/>
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <hr />
                    <div class="form-row float-right">
                        <div class="btn-group">
                            <input type="submit" value="Salvar" class="btn btn-outline-primary" />
                            <a class="btn btn-outline-secondary" asp-controller="Pais"  asp-action="Index">Voltar</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

SGD/Views/Pais/Index - Cópia.cshtml
@model IEnumerable<Pais>

@{
    ViewData["Title"] = "Listar Países";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Nome)</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Editar</a> |
                            <a class="btn btn-outline-info"><i class="bi bi-eye"></i>Detalhes</a> |
                            <a class="btn btn-danger text-white"><i class="bi bi-trash"></i>Excluir</a> 
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SGD/Views/Pais/Index.cshtml
@model IEnumerable<Pais>

@{
    ViewData["Title"] = "Listar Países";
}

<div id="categoriaIndex">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.ActionLink("Nome", "Index", new { sortOrdery = ViewBag.sortOrder == null ? "Asc" : (ViewBag.sortOrder == "Asc" ? "Desc" : "Asc") }, new { @style = "color: #000" })</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="strongTd"><a asp-controller="Pais" asp-action="Details" asp-route-id="@item.Id" style="color: #000">@item.Nome</a></td>
                    <td class="align-middle float-right"><a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Editar</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="Pais" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i>
         Novo 
    </a>
</div>

SGD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"> @*Icons*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SGD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> 
                @*CHANGE MENU*@
                    <ul class="navbar-nav flex-grow-1">  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-menu"></i> Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Cadastro
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Categoria" asp-action="Index"><i class="bi bi-list"></i> Categoria</a>
                                <a class="dropdown-item" asp-controller="SubCategoria" asp-action="Index"><i class="bi bi-list"></i> Sub-Categoria</a>
                                <a class="dropdown-item" asp-controller="Pais" asp-action="Index"><i class="bi bi-list"></i> País</a>
                            </div>
                        </li>
                    </ul>                    

                    <form class="form-inline my-2 my-lg-0" asp-controller="Home" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for...">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SGD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>